### ISSUE TITLE
PC Version can no longer be compiled due to deprecated functions

### ISSUE THREAD

**Issue by oncoremarco** [Gamebunn/Cream64_PC#6]
It seems that "unary_function" has been deprecated, therefore rendering the game impossible to compile.
![deprecated](https://github.com/Gamebunn/Cream64_PC/assets/60948196/c0f0a1b7-3529-4bce-a101-1c724c41ab30)

I was able to compile the standard version of sm64ex just fine.

**Comment by Gamebunn** [comment]
It's strange cause I've seen that same error before when doing a fresh compile myself but then it just keeps going like normal and finishes the compile. I didn't get that bottom part of your error at all so I'm not sure what's going on. 

EDIT: ok Aloxado found the issue (latest versions of gcc cause the issue, I'm on an older version hence why it just works fine) so hoping he can get to a fix soon to that and the unary warnings.

![image](https://github.com/Gamebunn/Cream64_PC/assets/72048631/e0e35ade-716f-49f1-b4cb-fc647068d31f)

**Comment by AloXado320** [comment]
Seems to be that GCC 14 onwards causes armips to no longer compile, luckily the fix is the same as the libaudiofile fix in sm64ex (using `gnu++11` instead of `c++11`).
I also properly fixed the warnings of `std::unary_function` using a patch provided in the issues of libaudiofile.
Those fixes will be merged asap in sm64ex-alo and I'll update the repo with those changes while at it.
![image](https://github.com/Gamebunn/Cream64_PC/assets/38191089/534c5ecc-5cdf-4c65-b66a-4e26a582eba6)

**Comment by AloXado320** [comment]
Repo has been updated to latest sm64ex-alo and now it compiles without problems.
